"""
Merchant fraud investigation agent.

This module provides the application-facing AI orchestration layer for
merchant fraud investigations.

The agent:
    - accepts a natural-language investigation question,
    - selects the appropriate merchant investigation tools,
    - retrieves deterministic results through MerchantService,
    - synthesizes the evidence into a structured investigation report.

The LLM does not access Spark, Delta tables, or SQL directly.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from langchain.agents import create_agent
from langchain_core.messages import AIMessage, BaseMessage
from langchain_openai import ChatOpenAI

from agentic_fraud.services.merchant_service import MerchantService
from agentic_fraud.tools.investigative_toolkit import (
    MerchantInvestigationToolkit,
    create_investigation_toolkit,
)


DEFAULT_MODEL_NAME = "gpt-4.1-mini"
DEFAULT_TEMPERATURE = 0.0


BASE_SYSTEM_PROMPT = """
You are an explainable fraud investigation assistant supporting merchant-level
fraud analysis.

Your responsibility is to investigate merchant fraud activity using only the
analytical tools provided to you.

You must treat tool results as the authoritative source for all
merchant-specific facts.

CORE RESPONSIBILITIES

1. Understand the user's investigation question.
2. Select only the tools necessary to answer it.
3. Retrieve factual merchant information through the tools.
4. Distinguish verified evidence from analytical interpretation.
5. Produce a concise, structured merchant investigation report.

DATA ACCESS AND GOVERNANCE RULES

- Never generate SQL.
- Never claim to query Spark, Databricks, Delta Lake, or database tables
  directly.
- Never invent merchants, transactions, metrics, percentages, peer results,
  risk signals, or financial amounts.
- Never infer a missing numeric value.
- Use only information returned by the registered investigation tools.
- A merchant name alone may not uniquely identify a merchant.
- Preserve merchant location and MCC context when reporting findings.
- If a tool reports that a merchant was not found, state that clearly.
- If the available information is insufficient, explain what information is
  missing rather than guessing.
- Do not provide legal, regulatory, or final fraud-adjudication conclusions.
- Frame recommendations as follow-up analysis or manual-review suggestions.

TOOL-USAGE RULES

- Begin with the merchant risk profile when baseline merchant statistics are
  needed.
- Use peer comparison when determining whether the merchant appears unusual
  relative to comparable merchants.
- Use risk-signal analysis when explaining why activity may be suspicious.
- Use high-risk transactions only when transaction-level evidence is useful.
- Do not call every tool automatically.
- Do not repeat the same tool call unless the earlier result was incomplete
  and a materially different request is required.
- Do not present a tool error as a successful investigation result.

REPORT FORMAT

When sufficient evidence is available, structure the response as:

## Merchant Investigation Report

### Merchant
Identify the merchant using the verified name, location, and MCC when
available.

### Executive Summary
Summarize the most important verified findings in a few sentences.

### Merchant Risk Profile
Present the relevant merchant-level metrics returned by the tools.

### Peer Assessment
Include this section only when peer-comparison evidence was retrieved.

### Risk Signals
Include this section only when risk-signal evidence was retrieved.

### Supporting Transactions
Include this section only when transaction-level evidence was retrieved.
Do not list transactions that were not returned by a tool.

### Assessment
Explain what the verified evidence indicates. Clearly distinguish this
interpretation from the factual tool output.

### Recommended Follow-Up
Provide a concise, non-prescriptive recommendation such as further analysis,
manual review, or continued monitoring.

Keep the report focused. Avoid generic fraud commentary that is not connected
to the retrieved evidence.
""".strip()


@dataclass(frozen=True)
class MerchantInvestigationResult:
    """
    Application-level result returned by MerchantInvestigationAgent.

    Attributes:
        question:
            Original investigation question.
        report:
            Final natural-language report generated by the agent.
        messages:
            Complete LangChain message history for observability and debugging.
    """

    question: str
    report: str
    messages: tuple[BaseMessage, ...]


class MerchantInvestigationAgent:
    """
    AI orchestration layer for merchant fraud investigations.

    This class owns:
        - model configuration,
        - system-prompt construction,
        - toolkit registration,
        - agent invocation,
        - final-response extraction.

    It deliberately does not own:
        - Spark access,
        - SQL generation,
        - merchant-domain calculations,
        - LangChain tool implementations.
    """

    def __init__(
        self,
        merchant_service: MerchantService,
        model_name: str = DEFAULT_MODEL_NAME,
        temperature: float = DEFAULT_TEMPERATURE,
        model: ChatOpenAI | None = None,
    ) -> None:
        """
        Initialize the merchant investigation agent.

        Args:
            merchant_service:
                Validated domain service used by the investigation tools.
            model_name:
                OpenAI model name used when a model instance is not injected.
            temperature:
                Model temperature. Fraud investigations should normally use
                zero or another low value for consistent responses.
            model:
                Optional preconfigured ChatOpenAI instance. This supports
                dependency injection and easier testing.

        Raises:
            TypeError:
                If merchant_service is missing.
            ValueError:
                If model_name is blank or temperature is invalid.
        """
        if merchant_service is None:
            raise TypeError("merchant_service must not be None.")

        normalized_model_name = model_name.strip()

        if not normalized_model_name:
            raise ValueError("model_name must not be blank.")

        if not 0.0 <= temperature <= 2.0:
            raise ValueError(
                "temperature must be between 0.0 and 2.0."
            )

        self._merchant_service = merchant_service

        self._toolkit: MerchantInvestigationToolkit = (
            create_investigation_toolkit(
                merchant_service=self._merchant_service
            )
        )

        self._model = model or ChatOpenAI(
            model=normalized_model_name,
            temperature=temperature,
        )

        self._system_prompt = self._build_system_prompt()

        self._agent = create_agent(
            model=self._model,
            tools=self._toolkit.get_tools(),
            system_prompt=self._system_prompt,
        )

    def investigate(
        self,
        question: str,
    ) -> MerchantInvestigationResult:
        """
        Run a merchant fraud investigation.

        Args:
            question:
                Natural-language merchant investigation request.

        Returns:
            MerchantInvestigationResult containing the final report and the
            complete agent message history.

        Raises:
            ValueError:
                If the question is blank.
            RuntimeError:
                If the agent returns no messages or no final AI response.
        """
        normalized_question = question.strip()

        if not normalized_question:
            raise ValueError("question must not be blank.")

        result: dict[str, Any] = self._agent.invoke(
            {
                "messages": [
                    {
                        "role": "user",
                        "content": normalized_question,
                    }
                ]
            }
        )

        messages = self._extract_messages(result)
        report = self._extract_final_report(messages)

        return MerchantInvestigationResult(
            question=normalized_question,
            report=report,
            messages=messages,
        )

    def investigate_text(
        self,
        question: str,
    ) -> str:
        """
        Run an investigation and return only the final report text.

        This is a convenience method for notebooks, APIs, or simple demos.

        Args:
            question:
                Natural-language merchant investigation request.

        Returns:
            Final investigation report.
        """
        return self.investigate(question).report

    def get_toolkit(self) -> MerchantInvestigationToolkit:
        """
        Return the investigation toolkit used by the agent.
        """
        return self._toolkit

    def get_tool_names(self) -> tuple[str, ...]:
        """
        Return the investigation tools visible to the agent.
        """
        return self._toolkit.get_tool_names()

    def get_system_prompt(self) -> str:
        """
        Return the complete agent system prompt.

        This is useful for validation, documentation, and observability.
        """
        return self._system_prompt

    def _build_system_prompt(self) -> str:
        """
        Combine general agent instructions with toolkit-specific strategy.
        """
        return (
            f"{BASE_SYSTEM_PROMPT}\n\n"
            f"{self._toolkit.get_strategy_prompt()}"
        )

    @staticmethod
    def _extract_messages(
        result: dict[str, Any],
    ) -> tuple[BaseMessage, ...]:
        """
        Extract and validate the message history returned by the agent.
        """
        raw_messages = result.get("messages")

        if not raw_messages:
            raise RuntimeError(
                "The merchant investigation agent returned no messages."
            )

        return tuple(raw_messages)

    @staticmethod
    def _extract_final_report(
        messages: tuple[BaseMessage, ...],
    ) -> str:
        """
        Extract the final non-empty AI response from the message history.

        LangChain agent state contains user, AI, and tool messages. We search
        backward for the final AIMessage containing displayable content.
        """
        for message in reversed(messages):
            if not isinstance(message, AIMessage):
                continue

            report = MerchantInvestigationAgent._content_to_text(
                message.content
            )

            if report:
                return report

        raise RuntimeError(
            "The merchant investigation agent did not return a final "
            "AI-generated report."
        )

    @staticmethod
    def _content_to_text(content: Any) -> str:
        """
        Convert supported LangChain message content into plain text.

        Message content is commonly a string, but some model configurations
        return a list of typed content blocks.
        """
        if isinstance(content, str):
            return content.strip()

        if not isinstance(content, list):
            return str(content).strip() if content is not None else ""

        text_parts: list[str] = []

        for block in content:
            if isinstance(block, str):
                normalized_block = block.strip()

                if normalized_block:
                    text_parts.append(normalized_block)

                continue

            if not isinstance(block, dict):
                continue

            block_type = block.get("type")

            if block_type in {"text", "output_text"}:
                block_text = block.get("text", "")

                if isinstance(block_text, str) and block_text.strip():
                    text_parts.append(block_text.strip())

        return "\n".join(text_parts).strip()


def create_merchant_investigation_agent(
    merchant_service: MerchantService,
    model_name: str = DEFAULT_MODEL_NAME,
    temperature: float = DEFAULT_TEMPERATURE,
    model: ChatOpenAI | None = None,
) -> MerchantInvestigationAgent:
    """
    Factory for constructing a MerchantInvestigationAgent.

    Args:
        merchant_service:
            Merchant-domain service used by the investigation toolkit.
        model_name:
            OpenAI model name used when no model is injected.
        temperature:
            Model temperature.
        model:
            Optional preconfigured ChatOpenAI dependency.

    Returns:
        Configured MerchantInvestigationAgent.
    """
    return MerchantInvestigationAgent(
        merchant_service=merchant_service,
        model_name=model_name,
        temperature=temperature,
        model=model,
    )